name: 02 - Eventos
on:
  workflow_dispatch:
  #push:
  #pull_request:
  #schedule:
    # Agendado para ejecutarse una única vez el día 03 de marzo de 2026 a las 00:00 UTC
    #- cron: '0 0 3 3 *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ShowTrigger
        run: |
          echo "Evento: ${{ github.event_name }}"