name: 05 & 06 - Filters and Activity Types
on:
  - workflow_dispatch
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
        - name: Print message
          run: echo 'Workflow triggered by filters or activity types'